### ISSUE TITLE
Make plan of action

### ISSUE THREAD

**Issue by jack-mil** [jack-mil/ER-Simulator#1]
We need to decide what tasks need to be completed by each member

**Comment by KorbinMDavis** [comment]
Here is the list of tasks as far as I can tell:

- Design the main loop structure and how the simulation runs (i.e. when does it create new patients, how does it store the data, what operations does it do and when)

- Write the Driver for the simulation and the front-end User Interactions

- Create the Patient class and all of its methods

- Test the parts of the project, handle any exceptions that should arise, and set up the program to be as secure as specified by the customer

- Add in the data analytics and necessary outputs

This is a relatively vague and overarching list, so if I missed anything please let me know. Once we decide how to handle each of these tasks (doing one of these at a time and splitting it up or splitting up multiple of these tasks at once to different members), we can assign members to tasks.

Does anyone want to volunteer to do any particular thing in the project?

**Comment by Jacob-pixel-hash** [comment]
This is subject to discussion, but I would like to write the driver file and front-end User interactions or help do so if everyone is ok with that
