### ISSUE TITLE
Create Patient class with Priority Queue compatibility

### ISSUE THREAD

**Issue by jack-mil** [jack-mil/ER-Simulator#3]
My task

**Comment by jack-mil** [comment]
I have added some potential ways of working with a `Patient` Class. The priority weight equation will definitely need to be tweaked.
The random urgency rating distribution should probably also be checked for correctness.

**Comment by KorbinMDavis** [comment]
Awesome! I'll check out the equation and the distribution tomorrow. I can check the math out and also run a quick monte carlo simulation on it to verify. Thank you Jackson! 👍
