### ISSUE TITLE
Create ER Rooms class (Modified Linked List Data Structure)

### ISSUE THREAD

**Issue by KorbinMDavis** [jack-mil/ER-Simulator#5]
Create a modified Linked List class with:
- [x] Cap for maximum number of nodes
- [x] Nodes with a Patient object and a countdown for when the room is empty again
- [x] Rooms (nodes) added at the end of the list when a new patient is called back
- [x] Rooms (nodes) deleted from anywhere in the list when a patient is finished in the room
- [x] A value that sticks with the list for the maximum number of rooms it has used as well as the maximum number of vacancies

**Comment by jack-mil** [comment]
Commit 2ee7dabbbb68a8f3ba720459c0fd023331821cac includes my initial attempt to produce this functionality.
Still left to be done:
- Testing everything works correctly. I haven't had a chance to do this yet, but wanted to let y'all (@KorbinMDavis  and @lochNesso) look over the methods and see if things should be renamed / reorganized
- Make room occupancy time have a chance to be longer than base amount. This would happen in the Room inner class constructor
